### ISSUE TITLE
Some URL are not loading list

### ISSUE THREAD

**Issue by ominfowave** [wseemann/JavaPlaylistParser#2]
I have found some URL for example 
`http://yayin.damarfm.com/damarfm.asx` 
` http://stream01.warm.fm:9002/listen.pls` 

when i have tested it's streaming URL not a list,but as it have extension .asx or .pls application consider it as list and try to load data from that due to that it goes to infinite loop in function 
 `parsePlaylist(String uri, InputStream stream, Playlist playlist) `   at
`	while ((line = reader.readLine()) != null)`

is they solution for avoid such link or how to identify this type of link??

**Comment by ominfowave** [comment]
any update for this??

**Comment by wseemann** [comment]
This isn't really an issue with my library. These servers are sending files with the wrong extension and content type. The urls should not include a playlist extension if they are actually audio streams and they should also not return invalid content types.

**Comment by ominfowave** [comment]
@wseemann  you are right,is they solution for this,have search lot nothing found related to that.any kind of help accepted if possible. is it possible to timeout  parsing process means if within X time parsing have not completed terminate the process?

**Comment by wseemann** [comment]
Yes, you can wrap your parsing calls and run that code as a `Thread`. Set a timer and if the playlist hasn't been parsed within that time you can kill the thread.
